import { defineInt, defineString } from 'firebase-functions/params';

const CONFIG_TIMEOUT = defineInt('CONFIG_TIMEOUT');
const CONFIG_TIMEOUT_PARSER = defineInt('CONFIG_TIMEOUT_PARSER');

const CONFIG_MEMORY = defineInt('CONFIG_MEMORY');
const CONFIG_MEMORY_TASKS = defineInt('CONFIG_MEMORY_TASKS');
const CONFIG_MININSTANCE = defineInt('CONFIG_MININSTANCE');
const REGION = defineString('REGION');

export const envDeploy = {
  NODE_ENV: process.env.NODE_ENV,
  CONFIG_TIMEOUT: CONFIG_TIMEOUT,
  CONFIG_TIMEOUT_PARSER: CONFIG_TIMEOUT_PARSER,
  CONFIG_MEMORY: CONFIG_MEMORY,
  CONFIG_MEMORY_TASKS: CONFIG_MEMORY_TASKS,
  CONFIG_MININSTANCE: CONFIG_MININSTANCE,
  REGION: REGION,
};
