export const env = {
  NODE_ENV: process.env.NODE_ENV,
  ORCID_CLIENT_ID: process.env.ORCID_CLIENT_ID,
  ORCID_SECRET: process.env.ORCID_SECRET,
  OUR_TOKEN_SECRET: process.env.OUR_TOKEN_SECRET,
  TWITTER_API_KEY: process.env.TWITTER_API_KEY,
  TWITTER_API_SECRET_KEY: process.env.TWITTER_API_SECRET_KEY,
  TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID,
  TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET,
  TWITTER_BEARER_TOKEN: process.env.TWITTER_BEARER_TOKEN,
  LOG_LEVEL_MSG: process.env.LOG_LEVEL_MSG,
  LOG_LEVEL_OBJ: process.env.LOG_LEVEL_OBJ,
};
