import {
  defineBoolean,
  defineSecret,
  defineString,
} from 'firebase-functions/params';

const PROJECT_ID = defineString('PROJECT_ID');

const ORCID_REDIRECT_URL = defineString('ORCID_REDIRECT_URL');
const TWITTER_CALLBACK_URL = defineString('TWITTER_CALLBACK_URL');
const TWITTER_REVOKE_URL = defineString('TWITTER_REVOKE_URL');
const FUNCTIONS_PY_URL = defineString('FUNCTIONS_PY_URL');
const NANOPUBS_PUBLISH_SERVERS = defineString('NANOPUBS_PUBLISH_SERVERS');
const FETCH_RATE_LIMIT_MS = defineString('FETCH_RATE_LIMIT_MS');

const ORCID_CLIENT_ID = defineString('ORCID_CLIENT_ID');
const TWITTER_CLIENT_ID = defineString('TWITTER_CLIENT_ID');
const NP_PUBLISH_RSA_PUBLIC_KEY = defineString('NP_PUBLISH_RSA_PUBLIC_KEY');

const USE_REAL_PARSER = defineBoolean('USE_REAL_PARSER');
const USE_REAL_TWITTERX = defineBoolean('USE_REAL_TWITTERX');
const USE_REAL_NANOPUB = defineBoolean('USE_REAL_NANOPUB');
const USE_REAL_NOTIFICATIONS = defineBoolean('USE_REAL_NOTIFICATIONS');

const ORCID_SECRET = defineSecret('ORCID_SECRET');
const OUR_TOKEN_SECRET = defineSecret('OUR_TOKEN_SECRET');
const TWITTER_CLIENT_SECRET = defineSecret('TWITTER_CLIENT_SECRET');

const NP_PUBLISH_RSA_PRIVATE_KEY = defineSecret('NP_PUBLISH_RSA_PRIVATE_KEY');

export const envRuntime = {
  NODE_ENV: process.env.NODE_ENV,
  REGION: process.env.FUNCTION_REGION,
  PROJECT_ID: PROJECT_ID,
  ORCID_REDIRECT_URL: ORCID_REDIRECT_URL,
  TWITTER_CALLBACK_URL: TWITTER_CALLBACK_URL,
  TWITTER_REVOKE_URL: TWITTER_REVOKE_URL,
  FUNCTIONS_PY_URL: FUNCTIONS_PY_URL,
  FETCH_RATE_LIMIT_MS: FETCH_RATE_LIMIT_MS,
  ORCID_CLIENT_ID: ORCID_CLIENT_ID,
  ORCID_SECRET: ORCID_SECRET,
  OUR_TOKEN_SECRET: OUR_TOKEN_SECRET,
  TWITTER_CLIENT_ID: TWITTER_CLIENT_ID,
  TWITTER_CLIENT_SECRET: TWITTER_CLIENT_SECRET,
  USE_REAL_PARSER: USE_REAL_PARSER,
  USE_REAL_TWITTERX: USE_REAL_TWITTERX,
  USE_REAL_NANOPUB: USE_REAL_NANOPUB,
  USE_REAL_NOTIFICATIONS: USE_REAL_NOTIFICATIONS,
  NANOPUBS_PUBLISH_SERVERS: NANOPUBS_PUBLISH_SERVERS,
  NP_PUBLISH_RSA_PRIVATE_KEY: NP_PUBLISH_RSA_PRIVATE_KEY,
  NP_PUBLISH_RSA_PUBLIC_KEY: NP_PUBLISH_RSA_PUBLIC_KEY,
};
